[package]
name = "bosskey-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "bosskey_config_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
bosskey-common = { path = "../../../crates/common" }
bosskey-core = { path = "../../../crates/core" }
tauri-plugin-single-instance = "2.4.2"
verhub-sdk = { workspace = true }
